Consider the SMS Spam Collection dataset, implement a python program to analyze
the syntactical patterns (word frequency, sentence length, POS tagging distribution)
and investigate their role in classifying messages as spam or ham (non-spam).

In [2]:
import pandas as pd
pd.options.display.max_colwidth = 200
import re
import nltk
from nltk.corpus import stopwords
from collections import Counter

In [3]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [8]:
import codecs
sourceFileName = "datasets/spam.csv"
targetFileName = "datasets/spam2.csv"
BLOCKSIZE = 1048576 # or some other, desired size in bytes
with codecs.open(sourceFileName, "r", "iso-8859-1") as sourceFile:
    with codecs.open(targetFileName, "w", "utf-8") as targetFile:
        while True:
            contents = sourceFile.read(BLOCKSIZE)
            if not contents:
                break
            targetFile.write(contents)

In [15]:
sms_collection = pd.read_csv("datasets/spam2.csv", sep = ",")

In [16]:
sms_collection = sms_collection.drop(columns = ["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"])

In [22]:
sms_collection = sms_collection.rename(columns = {"v1":"Label", "v2":"Message"})

In [24]:
sms_collection

,Label,Message
0,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives around here though"
...,...,...
5567,spam,"This is the 2nd time we have tried 2 contact u. U have won the å£750 Pound prize. 2 claim is easy, call 087187272008 NOW1! Only 10p per minute. BT-national-rate."
5568,ham,Will Ì_ b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other suggestions?"
5570,ham,The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free
5571,ham,Rofl. Its true to its name

In [25]:
stopwords_set = set(stopwords.words("english"))

In [28]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^0-9a-zA-Z]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    text = " ".join(word for word in text.split() if word not in stopwords_set)
    return text

In [29]:
sms_collection["Message"] = sms_collection['Message'].apply(clean_text)

In [31]:
sms_collection["Sentence_Length"] = sms_collection["Message"].apply(lambda x: len(x))

In [32]:
sms_collection

,Label,Message,Sentence_Length
0,ham,go jurong point crazy available bugis n great world la e buffet cine got amore wat,82
1,ham,ok lar joking wif u oni,23
2,spam,free entry 2 wkly comp win fa cup final tkts 21st may 2005 text fa 87121 receive entry question std txt rate c apply 08452810075over18,134
3,ham,u dun say early hor u c already say,35
4,ham,nah think goes usf lives around though,38
...,...,...,...
5567,spam,2nd time tried 2 contact u u 750 pound prize 2 claim easy call 087187272008 now1 10p per minute bt national rate,112
5568,ham,b going esplanade fr home,25
5569,ham,pity mood suggestions,21
5570,ham,guy bitching acted like interested buying something else next week gave us free,79
5571,ham,rofl true name,14

In [33]:
sentence = sms_collection["Message"][0]

In [34]:
sentence

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

In [36]:
pos = nltk.pos_tag(nltk.word_tokenize(sentence))

In [42]:
pos_freq = Counter(tag for _, tag in pos)

In [43]:
pos_freq

Counter({'NN': 6, 'JJ': 5, 'RB': 2, 'VB': 1, 'VBP': 1, 'VBD': 1})

In [ ]:
for sentence in sms_collection["Message"]:
    pos = nltk.pos_tag(nltk.word_tokenize(sentence))
    pos_freq = Counter(tag for _, tag in pos)